import React, { Component } from 'react'
import { getRandomColor } from './randomColorGenerator.js'
import Child from './Child'

class Parent extends Component {

  constructor() {
    super()
    this.state = {
      color: getRandomColor(),
      childrenColor: "#FFF",
    };
  }

  changeColor = (newChildColor) => {
    this.setState({
      color: getRandomColor(),
      childrenColor: newChildColor,
    });
  };

  render() {
    return (
      <div className="parent" style={{backgroundColor: this.state.color}}>
        <Child color={this.state.childrenColor} handleColorChange={this.changeColor}/>
        <Child color={this.state.childrenColor} handleColorChange={this.changeColor}/>
      </div>
    )
  }
}

export default Parent

//this component renders two child components and then this Parent component is rendered in App
//in render() the background color of the parent class is set to a random color generated by getRandomColor()
//Child color={this.state.childrenColor} handleColorChange={this.changeColor}
    //will start with the color set in this.state children color which is white
    //wgen clicked(defined in handleColorChange), it will change parent to a random color
//changeColor is the increment that causes to change the color to a random color set by the getRandomColor()
